openapi: 3.2.0
info:
  description: Volumez orchestrator API
  title: Volumez Alerts API
  version: 1.0.0 - 8d1ee8c4
  x-squire-version: 1.54.0
servers:
- url: https://api.dev.volumez.com
tags:
- description: ''
  name: Alerts
paths:
  /alerts:
    get:
      operationId: AlertsList
      parameters:
      - explode: true
        in: query
        name: capacity
        required: false
        schema:
          type: boolean
        style: form
      - explode: false
        in: header
        name: authorization
        required: false
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Alert'
                type: array
          description: List of alerts
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error getting a list of alerts
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error getting a list of alerts
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error getting a list of alerts
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
      security:
      - storage.io-authorizer: []
      summary: Get a list of alerts
      tags:
      - Alerts
      x-amazon-apigateway-integration:
        httpMethod: get
        uri: http://vlz-main-nlb-18ba9f518fe57637.elb.us-east-1.amazonaws.com:8991:8000/alerts
        passthroughBehavior: when_no_match
        type: http_proxy
        timeoutInMillis: 29000
        requestParameters:
          integration.request.header.X-Request-ID: context.requestId
          integration.request.querystring.capacity: method.request.querystring.capacity
    options:
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Methods:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Headers:
              explode: false
              schema:
                type: string
              style: simple
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 500 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 400 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 404 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 202 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 409 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS,POST,PATCH,DELETE'''
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: when_no_match
        type: mock
      tags:
      - Alerts
      summary: Describe alerts
      x-summary-source: derived
      operationId: optionsAlerts
      x-operation-id-source: derived
  /alerts/{alert}/acknowledge:
    options:
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Methods:
              explode: false
              schema:
                type: string
              style: simple
            Access-Control-Allow-Headers:
              explode: false
              schema:
                type: string
              style: simple
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 500 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 400 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 404 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 202 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 409 response
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS,POST,PATCH,DELETE'''
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: when_no_match
        type: mock
      tags:
      - Alerts
      summary: Describe alerts by alert acknowledge
      x-summary-source: derived
      operationId: optionsAlertsByAlertAcknowledge
      x-operation-id-source: derived
    post:
      operationId: AlertAcknowledge
      parameters:
      - explode: false
        in: path
        name: alert
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: authorization
        required: false
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegularResponse'
          description: Alert was successfully acknowledged
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error acknowledging alert
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error acknowledging alert
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error acknowledging alert
          headers:
            Access-Control-Allow-Origin:
              explode: false
              schema:
                type: string
              style: simple
      security:
      - storage.io-authorizer: []
      summary: Acknowledge a pending alert
      tags:
      - Alerts
      x-amazon-apigateway-integration:
        httpMethod: post
        uri: http://vlz-main-nlb-18ba9f518fe57637.elb.us-east-1.amazonaws.com:8991:8000/alerts/{alert}/acknowledge
        passthroughBehavior: when_no_match
        type: http_proxy
        timeoutInMillis: 29000
        requestParameters:
          integration.request.header.X-Request-ID: context.requestId
          integration.request.path.alert: method.request.path.alert
components:
  schemas:
    ErrorResponse:
      example:
        message: message
      properties:
        message:
          type: string
          x-omitempty: false
          x-isnullable: false
      type: object
    Alert:
      example:
        severity: Info
        cleartime: cleartime
        lastsendtime: lastsendtime
        details: details
        alertid: alertid
        state: Active
        creationtime: creationtime
        type: StateChange
        objecttype: Media
        objectid: objectid
      properties:
        alertid:
          minLength: 1
          readOnly: true
          title: Alert ID
          type: string
        type:
          enum:
          - StateChange
          - ProcessFailed
          - ThresholdReached
          minLength: 1
          readOnly: true
          title: Alert Type
          type: string
        state:
          enum:
          - Active
          - Acknowledged
          - Cleared
          minLength: 1
          readOnly: true
          title: Alert State
          type: string
        severity:
          enum:
          - Info
          - Warning
          - Critical
          - Fatal
          minLength: 1
          readOnly: true
          title: Alert Severity
          type: string
        objecttype:
          enum:
          - Media
          - Node
          - Volume
          - Snapshot
          - Attachment
          minLength: 1
          readOnly: true
          title: Alert Underlying Object Type
          type: string
        objectid:
          minLength: 1
          readOnly: true
          title: Alert Underlying Object ID
          type: string
        creationtime:
          minLength: 1
          readOnly: true
          title: Alert Creation Time
          type: string
        lastsendtime:
          minLength: 1
          readOnly: true
          title: Alert Last Send Time
          type: string
        cleartime:
          minLength: 1
          readOnly: true
          title: Alert Clear Time
          type: string
        details:
          minLength: 1
          readOnly: true
          title: Alert Details (according to alert type)
          type: string
      type: object
    RegularResponse:
      example:
        Message: Message
      properties:
        Message:
          type: string
      type: object
  securitySchemes:
    storage.io-authorizer:
      in: header
      name: authorization
      type: apiKey
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        providerARNs:
        - arn:aws:cognito-idp:us-east-1:125714719355:userpool/us-east-1_Mk5LdUo2I
        type: cognito_user_pools
x-amazon-apigateway-gateway-responses:
  DEFAULT_5XX:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  UNAUTHORIZED:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  ACCESS_DENIED:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  RESOURCE_NOT_FOUND:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  THROTTLED:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  AUTHORIZER_FAILURE:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  AUTHORIZER_CONFIGURATION_ERROR:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  INVALID_API_KEY:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  BAD_REQUEST_PARAMETERS:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  BAD_REQUEST_BODY:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  REQUEST_TOO_LARGE:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  UNSUPPORTED_MEDIA_TYPE:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  API_CONFIGURATION_ERROR:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
  QUOTA_EXCEEDED:
    responseParameters:
      gatewayresponse.header.access-control-allow-origin: '''*'''
    responseTemplates:
      application/json: '{"Message":$context.error.messageString}'
x-original-swagger-version: '2.0'
